apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-api-storage
  namespace: ${.Namespace}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: wm2-nfs
