apiVersion: v1
kind: Secret
metadata:
  name: dify-credentials
  namespace: ${.Namespace}
data:
  # Base64 encoded postgres password, default is difyai123456
  pg-password: ${.PGPassword}
  # Base64 encoded redis password, default is difyai123456
  redis-password: ${.RedisPassword}
  # Base64 encoded init password, default is password
  init-password: ${.InitPassword}
type: Opaque
